---
- name: mysql backup | create backup directory
  become: true
  file:
    path: "{{ mysql_backup_dir }}"
    recurse: true
    state: directory

- name: mysql backup | create cron job
  become: true
  template:
    src: etc-crond-mysql-backup.j2
    dest: /etc/cron.{{ mysql_backup_frequency }}/mysql-backup
    mode: 0755
